language: python

python: 3.5
notifications:
  email: false
addons:
  ssh_known_hosts: adicu.com

cache:
  directories:
    - $HOME/.cache/pip
    - webpack/node_modules

install:
- pip install lektor
- gem install html-proofer
script:
- lektor build -f webpack -O _output
- htmlproofer _output --file-ignore "/events/201[456].*/"

before_deploy:
- test $TRAVIS_BRANCH == "master"

- openssl aes-256-cbc -K $encrypted_b4089b536350_key -iv $encrypted_b4089b536350_iv -in .ssh/deploy_rsa.enc -out .ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/.ssh/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/.ssh/deploy_rsa

- git config user.name "ADI-Bot"
- git config user.email "infrastructure@adicu.com"
- scripts/travis-commit.sh

deploy:
  provider: script
  script: lektor deploy beta
  on:
    branch: master
